### ISSUE TITLE
Are the shb_hardware/os/userappl strings zero-terminated?

### ISSUE THREAD

**Issue by hadrielk** [pcapng/pcapng#27]
The doc doesn't say, so we need to clear that up. Wireshark does not add a null to them, fwiw.

**Comment by guyharris** [comment]
No strings are described as null-terminated; some are explicitly described as not being null-terminated.

I've updated the spec in a356e3602dfa7067f4ed05bc8b5f4907aa833f53 to explicitly indicate that all strings for which we didn't indicate zero-termination are not zero-terminated.

I also changed them all to say "zero-terminated" rather than "null-terminated" or "with NULL termination".
